In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

ModuleNotFoundError: No module named 'pandas'

In [5]:
df_data = pd.read_csv(r"C:\Users\heumo\Machine learning\Hackaton\events.csv")
df_data

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2020-09-24 11:57:06 UTC,view,1996170,2144415922528452715,electronics.telephone,NaN,31.90,1515915625519388267,LJuJVLEjPT
1,2020-09-24 11:57:26 UTC,view,139905,2144415926932472027,computers.components.cooler,zalman,17.16,1515915625519380411,tdicluNnRY
2,2020-09-24 11:57:27 UTC,view,215454,2144415927158964449,NaN,NaN,9.81,1515915625513238515,4TMArHtXQy
3,2020-09-24 11:57:33 UTC,view,635807,2144415923107266682,computers.peripherals.printer,pantum,113.81,1515915625519014356,aGFYrNgC08
4,2020-09-24 11:57:36 UTC,view,3658723,2144415921169498184,NaN,cameronsino,15.87,1515915625510743344,aa4mmk0kwQ
...,...,...,...,...,...,...,...,...,...
885124,2021-02-28 23:55:01 UTC,view,953226,2144415927553229037,NaN,NaN,219.94,1515915625611023730,FRLqIttxKU
885125,2021-02-28 23:58:05 UTC,view,1715907,2144415927049912542,electronics.video.tv,starwind,80.03,1515915625611024014,g6WqPf50Ma
885126,2021-02-28 23:58:09 UTC,view,4170534,2144415939364389423,electronics.clocks,amazfit,64.92,1515915625611024020,xNIJBqZdkd
885127,2021-02-28 23:58:14 UTC,view,888273,2144415921932861531,electronics.telephone,NaN,10.16,1515915625611024030,9pCbKMIcSx
885128,2021-02-28 23:59:09 UTC,view,743182,2144415935631458761,construction.tools.soldering,kada,65.08,1515915625556087775,BejOXRngEW

In [6]:
df_data.columns

Index(['event_time', 'event_type', 'product_id', 'category_id',
       'category_code', 'brand', 'price', 'user_id', 'user_session'],
      dtype='object')

In [10]:
df_data.describe().T

,count,mean,std,min,25%,50%,75%,max
product_id,885129.0,1.906621e+06,1.458708e+06,1.020000e+02,6.988030e+05,1.452883e+06,3.721194e+06,4.183880e+06
category_id,885129.0,2.144423e+18,6.165105e+14,2.144416e+18,2.144416e+18,2.144416e+18,2.144416e+18,2.227847e+18
price,885129.0,1.463287e+02,2.968077e+02,2.200000e-01,2.646000e+01,6.571000e+01,1.904900e+02,6.477106e+04
user_id,885129.0,1.515916e+18,3.554165e+07,1.515916e+18,1.515916e+18,1.515916e+18,1.515916e+18,1.515916e+18

In [8]:
#VÃ©rifier les valeurs nulls du data set
df_data.isnull().sum()

event_time            0
event_type            0
product_id            0
category_id           0
category_code    236219
brand            212364
price                 0
user_id               0
user_session        165
dtype: int64

In [11]:
df_data.dtypes

event_time        object
event_type        object
product_id         int64
category_id        int64
category_code     object
brand             object
price            float64
user_id            int64
user_session      object
dtype: object

In [18]:
# Valeur unique de chaque colonne
#df_data.event_type.unique()
#df_data.user_session.unique()
df_data.category_code.unique()

array(['electronics.telephone', 'computers.components.cooler', nan,
       'computers.peripherals.printer', 'construction.tools.saw',
       'computers.desktop', 'computers.network.router',
       'electronics.video.tv', 'auto.accessories.player',
       'computers.components.motherboard', 'electronics.camera.video',
       'computers.peripherals.keyboard', 'computers.components.hdd',
       'electronics.audio.acoustic', 'computers.components.power_supply',
       'appliances.steam_cleaner', 'computers.components.cpu',
       'construction.tools.welding', 'appliances.kitchen.juicer',
       'computers.peripherals.scanner', 'computers.peripherals.camera',
       'electronics.tablet', 'computers.peripherals.nas',
       'stationery.cartrige', 'computers.components.network_adapter',
       'computers.peripherals.joystick', 'appliances.sewing_machine',
       'computers.peripherals.wifi', 'electronics.audio.dictaphone',
       'appliances.environment.vacuum', 'electronics.clocks',
       'electronics.audio.headphone', 'computers.components.videocards',
       'auto.accessories.alarm', 'appliances.kitchen.kettle',
       'furniture.living_room.shelving', 'computers.peripherals.mouse',
       'construction.tools.screw', 'construction.tools.pump',
       'auto.accessories.window', 'computers.components.tv_tuner',
       'kids.skates', 'computers.peripherals.vr',
       'construction.tools.soldering', 'computers.notebook',
       'appliances.kitchen.microwave', 'auto.accessories.radar',
       'accessories.bag', 'construction.tools.drill',
       'auto.accessories.parktronic', 'stationery.paper',
       'computers.peripherals.monitor', 'electronics.video.projector',
       'appliances.kitchen.coffee_machine', 'computers.ebooks',
       'appliances.kitchen.blender', 'stationery.battery',
       'electronics.audio.microphone', 'stationery.stapler',
       'appliances.kitchen.fryer', 'construction.tools.light',
       'country_yard.cultivator', 'appliances.iron',
       'appliances.environment.air_heater', 'auto.accessories.gps',
       'computers.components.cdrw', 'auto.accessories.videoregister',
       'appliances.kitchen.mixer', 'electronics.video.tv_remote',
       'apparel.glove', 'appliances.kitchen.washer',
       'appliances.kitchen.meat_grinder', 'appliances.kitchen.grill',
       'auto.accessories.compressor',
       'electronics.audio.music_tools.piano', 'construction.tools.wrench',
       'appliances.kitchen.steam_cooker',
       'appliances.kitchen.coffee_grinder',
       'appliances.personal.massager', 'country_yard.weather_station',
       'appliances.personal.hair_cutter',
       'computers.components.sound_card', 'construction.tools.heater',
       'kids.toys', 'appliances.environment.fan',
       'electronics.calculator', 'construction.tools.generator',
       'appliances.personal.scales', 'appliances.kitchen.toster',
       'medicine.tools.tonometer', 'construction.tools.painting',
       'furniture.bathroom.bath', 'sport.bicycle',
       'electronics.camera.photo', 'computers.gaming',
       'auto.accessories.immobilizer', 'country_yard.lawn_mower',
       'electronics.fax', 'country_yard.watering', 'jewelry.souvenir',
       'auto.accessories.light', 'jewelry.ring',
       'furniture.living_room.chair', 'appliances.kitchen.refrigerators',
       'accessories.briefcase', 'auto.accessories.winch',
       'furniture.kitchen.chair', 'furniture.bedroom.blanket'],
      dtype=object)

In [33]:
noms_separes = df_data['category_code'].str.split(',', expand=True)

In [39]:
# Fonction pour extraire les deux premiers et le dernier mot
def extraire_mots(chaine):
    mots = chaine.split()
    if len(mots) >= 3:
        return mots[0], mots[1], mots[-1]
    elif len(mots) == 2:
        return mots[0], mots[1], mots[1]
    elif len(mots) == 1:
        return mots[0], '', mots[0]
    else:
        return '', '', ''
    # Appliquer la fonction Ã  la colonne 'textes' et crÃ©er de nouvelles colonnes
df_data[['premier_mot', 'deuxieme_mot', 'dernier_mot']] = df_data['category_code'].apply(lambda x: pd.Series(extraire_mots(x)))

AttributeError: 'float' object has no attribute 'split'

In [38]:
# Appliquer la fonction Ã  la colonne 'textes' et crÃ©er de nouvelles colonnes
df_data[['premier_mot', 'deuxieme_mot', 'dernier_mot']] = df_data['category_code'].apply(lambda x: pd.Series(extraire_mots(x)))

# Afficher le DataFrame rÃ©sultant
print(df_data)

AttributeError: 'float' object has no attribute 'split'

In [41]:
# Fonction pour extraire les deux premiers et le dernier mot
def extraire_mots(chaine):
    mots = chaine.split(',')
    if len(mots) >= 3:
        return mots[0], mots[1], mots[-1]
    elif len(mots) == 2:
        return mots[0], mots[1], mots[1]
    elif len(mots) == 1:
        return mots[0], '', mots[0]
    else:
        return '', '', ''

# Appliquer la fonction Ã  la colonne 'category_code' et crÃ©er de nouvelles colonnes
df_data[['premier_mot', 'deuxieme_mot', 'dernier_mot']] = df_data['category_code'].apply(lambda x: pd.Series(extraire_mots(x)))

AttributeError: 'float' object has no attribute 'split'

In [47]:
# Fonction pour extraire les deux premiers et le dernier mot
def extraire_mots(chaine):
    if isinstance(chaine, str):  # VÃ©rifie si la valeur est une chaÃ®ne de caractÃ¨res
        mots = chaine.split('.')
        if len(mots) >= 3:
            return mots[0], mots[1], mots[-1]
        elif len(mots) == 2:
            return mots[0], mots[1], mots[1]
        elif len(mots) == 1:
            return mots[0], '', mots[0]
    return '', '', ''

# Convertir la colonne 'category_code' en chaÃ®nes de caractÃ¨res
df_data['category_code'] = df_data['category_code'].astype(str)

# Appliquer la fonction Ã  la colonne 'category_code' et crÃ©er de nouvelles colonnes
df_data[['premier_mot', 'deuxieme_mot', 'dernier_mot']] = df_data['category_code'].apply(lambda x: pd.Series(extraire_mots(x)))

In [48]:
df_data

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session,premier_mot,deuxieme_mot,dernier_mot
0,2020-09-24 11:57:06 UTC,view,1996170,2144415922528452715,electronics.telephone,NaN,31.90,1515915625519388267,LJuJVLEjPT,electronics,telephone,telephone
1,2020-09-24 11:57:26 UTC,view,139905,2144415926932472027,computers.components.cooler,zalman,17.16,1515915625519380411,tdicluNnRY,computers,components,cooler
2,2020-09-24 11:57:27 UTC,view,215454,2144415927158964449,nan,NaN,9.81,1515915625513238515,4TMArHtXQy,nan,,nan
3,2020-09-24 11:57:33 UTC,view,635807,2144415923107266682,computers.peripherals.printer,pantum,113.81,1515915625519014356,aGFYrNgC08,computers,peripherals,printer
4,2020-09-24 11:57:36 UTC,view,3658723,2144415921169498184,nan,cameronsino,15.87,1515915625510743344,aa4mmk0kwQ,nan,,nan
...,...,...,...,...,...,...,...,...,...,...,...,...
885124,2021-02-28 23:55:01 UTC,view,953226,2144415927553229037,nan,NaN,219.94,1515915625611023730,FRLqIttxKU,nan,,nan
885125,2021-02-28 23:58:05 UTC,view,1715907,2144415927049912542,electronics.video.tv,starwind,80.03,1515915625611024014,g6WqPf50Ma,electronics,video,tv
885126,2021-02-28 23:58:09 UTC,view,4170534,2144415939364389423,electronics.clocks,amazfit,64.92,1515915625611024020,xNIJBqZdkd,electronics,clocks,clocks
885127,2021-02-28 23:58:14 UTC,view,888273,2144415921932861531,electronics.telephone,NaN,10.16,1515915625611024030,9pCbKMIcSx,electronics,telephone,telephone
885128,2021-02-28 23:59:09 UTC,view,743182,2144415935631458761,construction.tools.soldering,kada,65.08,1515915625556087775,BejOXRngEW,construction,tools,soldering