In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [22]:
df_data = pd.read_csv(r"C:\Users\heumo\Machine learning\ProjetHack\events.csv")
df_data

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2020-09-24 11:57:06 UTC,view,1996170,2144415922528452715,electronics.telephone,NaN,31.90,1515915625519388267,LJuJVLEjPT
1,2020-09-24 11:57:26 UTC,view,139905,2144415926932472027,computers.components.cooler,zalman,17.16,1515915625519380411,tdicluNnRY
2,2020-09-24 11:57:27 UTC,view,215454,2144415927158964449,NaN,NaN,9.81,1515915625513238515,4TMArHtXQy
3,2020-09-24 11:57:33 UTC,view,635807,2144415923107266682,computers.peripherals.printer,pantum,113.81,1515915625519014356,aGFYrNgC08
4,2020-09-24 11:57:36 UTC,view,3658723,2144415921169498184,NaN,cameronsino,15.87,1515915625510743344,aa4mmk0kwQ
...,...,...,...,...,...,...,...,...,...
885124,2021-02-28 23:55:01 UTC,view,953226,2144415927553229037,NaN,NaN,219.94,1515915625611023730,FRLqIttxKU
885125,2021-02-28 23:58:05 UTC,view,1715907,2144415927049912542,electronics.video.tv,starwind,80.03,1515915625611024014,g6WqPf50Ma
885126,2021-02-28 23:58:09 UTC,view,4170534,2144415939364389423,electronics.clocks,amazfit,64.92,1515915625611024020,xNIJBqZdkd
885127,2021-02-28 23:58:14 UTC,view,888273,2144415921932861531,electronics.telephone,NaN,10.16,1515915625611024030,9pCbKMIcSx
885128,2021-02-28 23:59:09 UTC,view,743182,2144415935631458761,construction.tools.soldering,kada,65.08,1515915625556087775,BejOXRngEW

In [23]:
df_data.columns

Index(['event_time', 'event_type', 'product_id', 'category_id',
       'category_code', 'brand', 'price', 'user_id', 'user_session'],
      dtype='object')

In [24]:
df_data.describe().T

,count,mean,std,min,25%,50%,75%,max
product_id,885129.0,1.906621e+06,1.458708e+06,1.020000e+02,6.988030e+05,1.452883e+06,3.721194e+06,4.183880e+06
category_id,885129.0,2.144423e+18,6.165105e+14,2.144416e+18,2.144416e+18,2.144416e+18,2.144416e+18,2.227847e+18
price,885129.0,1.463287e+02,2.968077e+02,2.200000e-01,2.646000e+01,6.571000e+01,1.904900e+02,6.477106e+04
user_id,885129.0,1.515916e+18,3.554165e+07,1.515916e+18,1.515916e+18,1.515916e+18,1.515916e+18,1.515916e+18

## I Traitement des doublons

In [25]:
# Drop duplicate
df_data.drop_duplicates(inplace=True)

In [26]:

df_data.shape

(884474, 9)

## II Traitement des valuers manquantes

In [27]:
#VÃ©rifier les valeurs nulls du data set
df_data.isnull().sum()

event_time            0
event_type            0
product_id            0
category_id           0
category_code    236047
brand            212232
price                 0
user_id               0
user_session        162
dtype: int64

In [28]:
df_data.dtypes

event_time        object
event_type        object
product_id         int64
category_id        int64
category_code     object
brand             object
price            float64
user_id            int64
user_session      object
dtype: object

In [29]:
# Le pourcentage des valeurs manquantes
missing_percentages = (df_data.isna().sum() / len(df_data)).sort_values(ascending=False) * 100
print(f'{missing_percentages}%')

category_code    26.687839
brand            23.995279
user_session      0.018316
event_time        0.000000
event_type        0.000000
product_id        0.000000
category_id       0.000000
price             0.000000
user_id           0.000000
dtype: float64%

In [37]:
# Valeur unique de chaque colonne
#df_data.event_type.unique()
df_data.event_type.unique()
#df_data.category_code.unique()

array(['view', 'cart', 'purchase'], dtype=object)

In [31]:
'''
# Fonction pour extraire les deux premiers et le dernier mot
def extraire_mots(chaine):
    mots = chaine.split(,)
    if len(mots) >= 3:
        return mots[0], mots[1], mots[-1]
    elif len(mots) == 2:
        return mots[0], mots[1], mots[1]
    elif len(mots) == 1:
        return mots[0], '', mots[0]
    else:
        return '', '', ''

'''

"\n# Fonction pour extraire les deux premiers et le dernier mot\ndef extraire_mots(chaine):\n    mots = chaine.split(,)\n    if len(mots) >= 3:\n        return mots[0], mots[1], mots[-1]\n    elif len(mots) == 2:\n        return mots[0], mots[1], mots[1]\n    elif len(mots) == 1:\n        return mots[0], '', mots[0]\n    else:\n        return '', '', ''\n\n"

In [32]:
'''
# Appliquer la fonction Ã  la colonne 'textes' et crÃ©er de nouvelles colonnes
df_data[['premier_mot', 'deuxieme_mot', 'dernier_mot']] = df_data['category_code'].apply(lambda x: pd.Series(extraire_mots(x)))

# Afficher le DataFrame rÃ©sultant
print(df_data)
'''

"\n# Appliquer la fonction Ã  la colonne 'textes' et crÃ©er de nouvelles colonnes\ndf_data[['premier_mot', 'deuxieme_mot', 'dernier_mot']] = df_data['category_code'].apply(lambda x: pd.Series(extraire_mots(x)))\n\n# Afficher le DataFrame rÃ©sultant\nprint(df_data)\n"

In [35]:
# Fonction pour extraire les deux premiers et le dernier mot
def extraire_mots(chaine):
    if isinstance(chaine, str):  # VÃ©rifie si la valeur est une chaÃ®ne de caractÃ¨res
        mots = chaine.split('.')
        if len(mots) >= 3:
            return mots[0], mots[1], mots[-1]
        elif len(mots) == 2:
            return mots[0], mots[1], mots[1]
        elif len(mots) == 1:
            return mots[0], '', mots[0]
    return '', '', ''

# Convertir la colonne 'category_code' en chaÃ®nes de caractÃ¨res
df_data['category_code'] = df_data['category_code'].astype(str)

# Appliquer la fonction Ã  la colonne 'category_code' et crÃ©er de nouvelles colonnes
df_data[['categorie_1', 'categorie_2', 'categorie_3']] = df_data['category_code'].apply(lambda x: pd.Series(extraire_mots(x)))

In [34]:
df_data

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session,premier_mot,deuxieme_mot,dernier_mot
0,2020-09-24 11:57:06 UTC,view,1996170,2144415922528452715,electronics.telephone,NaN,31.90,1515915625519388267,LJuJVLEjPT,electronics,telephone,telephone
1,2020-09-24 11:57:26 UTC,view,139905,2144415926932472027,computers.components.cooler,zalman,17.16,1515915625519380411,tdicluNnRY,computers,components,cooler
2,2020-09-24 11:57:27 UTC,view,215454,2144415927158964449,nan,NaN,9.81,1515915625513238515,4TMArHtXQy,nan,,nan
3,2020-09-24 11:57:33 UTC,view,635807,2144415923107266682,computers.peripherals.printer,pantum,113.81,1515915625519014356,aGFYrNgC08,computers,peripherals,printer
4,2020-09-24 11:57:36 UTC,view,3658723,2144415921169498184,nan,cameronsino,15.87,1515915625510743344,aa4mmk0kwQ,nan,,nan
...,...,...,...,...,...,...,...,...,...,...,...,...
885124,2021-02-28 23:55:01 UTC,view,953226,2144415927553229037,nan,NaN,219.94,1515915625611023730,FRLqIttxKU,nan,,nan
885125,2021-02-28 23:58:05 UTC,view,1715907,2144415927049912542,electronics.video.tv,starwind,80.03,1515915625611024014,g6WqPf50Ma,electronics,video,tv
885126,2021-02-28 23:58:09 UTC,view,4170534,2144415939364389423,electronics.clocks,amazfit,64.92,1515915625611024020,xNIJBqZdkd,electronics,clocks,clocks
885127,2021-02-28 23:58:14 UTC,view,888273,2144415921932861531,electronics.telephone,NaN,10.16,1515915625611024030,9pCbKMIcSx,electronics,telephone,telephone
885128,2021-02-28 23:59:09 UTC,view,743182,2144415935631458761,construction.tools.soldering,kada,65.08,1515915625556087775,BejOXRngEW,construction,tools,soldering

In [ ]:
# tableau de correlation